### ISSUE TITLE
rand() doesn't generate zero

### ISSUE THREAD

**Issue by davidmisiak** [javierartero/vscode-equality#12]
When I enter `rand(-2, 2)`  multiple times with multi-cursor and hit Ctrl+Enter, something like this shows up:
```
1
2
=rand(-2, 2)
1
=rand(-2, 2)
1
2
2
-2
```

I tried it several times and I found out that no zero was generated. I assume that those `rand`s, that don't convert into numbers are exactly those which should be zeros, but they don't get converted for some reason.

**Comment by javierartero** [comment]
Thank you @davidmisiak  for the comment, in version 0.7.1 it should be fixed.
